import fs from "node:fs/promises";
import path from "node:path";

const [providerId] = process.argv.slice(2);

if (!providerId) {
  throw new Error("Usage: pnpm provider:new <provider-id>");
}

const packageDir = path.join(process.cwd(), "providers", providerId);
await fs.mkdir(path.join(packageDir, "src"), { recursive: true });

const packageName = `@openvitals/provider-${providerId}`;
const displayName = providerId
  .split("-")
  .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
  .join(" ");

await fs.writeFile(
  path.join(packageDir, "package.json"),
  JSON.stringify(
    {
      name: packageName,
      version: "0.1.0",
      type: "module",
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
      scripts: {
        build: "tsup src/index.ts --format esm --dts",
        test: "vitest run --passWithNoTests"
      },
      dependencies: {
        "@openvitals/contracts": "workspace:*",
        "@openvitals/runtime": "workspace:*"
      },
      openvitals: {
        kind: "provider",
        phase: "phase-1",
        provider: {
          id: providerId,
          class: "cloud",
          status: "scaffolded",
          runtimePath: "mock",
          coverage: []
        }
      }
    },
    null,
    2
  )
);

await fs.writeFile(
  path.join(packageDir, "src", "index.ts"),
  `import type { ProviderManifest } from "@openvitals/contracts";
import { ProviderManifestSchema } from "@openvitals/contracts";
import { createMockCollector } from "@openvitals/runtime";

export const manifest: ProviderManifest = ProviderManifestSchema.parse({
  id: ${JSON.stringify(providerId)},
  packageName: ${JSON.stringify(packageName)},
  displayName: ${JSON.stringify(displayName)},
  providerClass: "cloud",
  runtimePath: "mock",
  phase: "phase-1",
  status: "scaffolded",
  coverage: [],
  capabilities: ["connect", "sync_history", "sync_incremental"],
  notes: "Generated by pnpm provider:new."
});

export const collector = createMockCollector(manifest);
`
);

console.log(`Created provider scaffold at ${packageDir}`);
